# Generated by Django 6.0.2 on 2026-02-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_joining',
            field=models.DateField(auto_now_add=True),
        ),
    ]
