# Generated by Django 6.0.3 on 2026-03-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_productivitysnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='productivitysnapshot',
            name='correction_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productivitysnapshot',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
