# Generated by Django 6.0.2 on 2026-03-11 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('HALF_DAY', 'Half Day'), ('ABSENT', 'Absent'), ('ON_LEAVE', 'On Leave'), ('HOLIDAY', 'Holiday'), ('INACTIVE', 'Inactive')], default='ABSENT', max_length=20)),
                ('total_work_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_break_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_idle_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('net_work_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_late', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
