# Generated by Django 6.0.3 on 2026-03-12 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='working', max_length=20)),
            ],
        ),
        migrations.AddIndex(
            model_name='breaksession',
            index=models.Index(fields=['user', 'start_time'], name='user_sessio_user_id_4ea6ea_idx'),
        ),
        migrations.AddIndex(
            model_name='breaksession',
            index=models.Index(fields=['work_session', 'break_type'], name='user_sessio_work_se_9b1496_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['user', 'start_time'], name='user_sessio_user_id_fee192_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['start_time'], name='user_sessio_start_t_87b3d4_idx'),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='work_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='user_sessions.worksession'),
        ),
        migrations.AddIndex(
            model_name='heartbeat',
            index=models.Index(fields=['user', 'timestamp'], name='user_sessio_user_id_624e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='heartbeat',
            index=models.Index(fields=['work_session', 'timestamp'], name='user_sessio_work_se_98aff3_idx'),
        ),
    ]
