# Generated by Django 6.0.2 on 2026-03-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Global Policy', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('shift_start', models.TimeField(help_text='Expected shift start time')),
                ('shift_end', models.TimeField(help_text='Expected shift end time')),
                ('grace_period', models.PositiveIntegerField(default=15, help_text='Minutes allowed after shift start before marked late')),
                ('min_full_day_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('min_half_day_hours', models.DecimalField(decimal_places=2, default=4.0, max_digits=4)),
                ('max_idle_minutes', models.PositiveIntegerField(default=30, help_text='Idle threshold before flagging')),
                ('break_duration_limit', models.PositiveIntegerField(default=60, help_text='Max allowed break minutes per day')),
            ],
            options={
                'verbose_name_plural': 'Attendance Policies',
            },
        ),
    ]
